[project]
name = "uv-dependencie-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "unicorn>=2.1.3",
    "uvicorn>=0.34.3",
]
